#!/usr/bin/env python3

from sh import rbw, ssh_keygen, ErrorReturnCode
from pathlib import Path
import os, re, sys

KEY_PATTERN = re.compile(r" for(?: key)? '?(.+?)'?: ")
RBW_ARGS = ["--folder", "ssh"]

def bw_get(key: Path):
    passphrase_cmd = rbw("get", *RBW_ARGS, key.name, _ok_code=[0, 1])
    # Remove new line character
    passphrase = str(passphrase_cmd)[:-1]
    return passphrase

def bw_exists(key: Path):
    history_cmd = rbw("history", *RBW_ARGS, key.name, _ok_code=(0, 1))
    return history_cmd.exit_code == 0 or b"no entry found" not in history_cmd.stderr

def bw_gen(key: Path):
    generate_command = rbw("generate", *RBW_ARGS, "20", key.name)
    passphrase = str(generate_command)[:-1]
    return passphrase

def check_key(private_key: Path, passphrase: str):
    try:
        ssh_keygen(
            "-y", "-f", private_key, "-P", passphrase, _tty_out=False, _no_out=True
        )
        return True
    except ErrorReturnCode as ex:
        msg = ex.stderr.decode()
        print(f"Passphrase check failed: {msg}", file=sys.stderr)
        return False


def askpass():
    key = Path(KEY_PATTERN.search(sys.argv[1]).group(1))
    print(f"Reading passphrase from Bitwarden vault for {key}", file=sys.stderr)

    passphrase = bw_get(key)
    # We need to check the passphrase ourself,
    # otherwise, ssh-add will call us indefinitely.
    if not check_key(key, passphrase):
        sys.exit(1)
    print(passphrase, end="", flush=True)


def keygen():
    try:
        key = Path(sys.argv[sys.argv.index("-f") + 1])
    except:
        print("Key filename must be provided with -f", file=sys.stderr)
        sys.exit(1)
    if key.exists():
        print("Key already exists", file=sys.stderr)
        sys.exit(1)

    # Check if it exists
    if bw_exists(key):
        print("Passphrase entry already exists in your vault", file=sys.stderr)
        sys.exit(1)

    # Add passphrase in bitwarden first
    passphrase = bw_gen(key)
    try:
        ssh_keygen(*sys.argv[1:], "-N", passphrase, _fg=True)
    except:
        sys.exit(1)


if __name__ == "__main__":
    mode = Path(sys.argv[0]).name
    if "askpass" in mode:
        askpass()
    elif "keygen" in mode:
        keygen()
